apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
  labels:
    app: web-app
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - port: 80             # Port interne exposé par le service
      targetPort: 80      # Port sur lequel le conteneur écoute
      nodePort: 30007       # Port sur lequel le service sera accessible depuis l'extérieur du cluster